"""Create all tables from ERD

Revision ID: eec6aac093f9
Revises: 
Create Date: 2025-09-02 17:33:26.379590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec6aac093f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_weather',
    sa.Column('ground_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('month_date', sa.Date(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ground_pk')
    )
    op.create_table('item',
    sa.Column('item_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('item_pk')
    )
    op.create_table('location',
    sa.Column('local_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('local_pk')
    )
    op.create_table('item_retail',
    sa.Column('retail_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_pk', sa.Integer(), nullable=True),
    sa.Column('production', sa.Integer(), nullable=True),
    sa.Column('inbound', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('month_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['item_pk'], ['item.item_pk'], ),
    sa.PrimaryKeyConstraint('retail_pk')
    )
    op.create_table('sea_weather',
    sa.Column('sea_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('local_pk', sa.Integer(), nullable=True),
    sa.Column('month_date', sa.Date(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('salinity', sa.Float(), nullable=True),
    sa.Column('wave_height', sa.Float(), nullable=True),
    sa.Column('wave_period', sa.Float(), nullable=True),
    sa.Column('wave_speed', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['local_pk'], ['location.local_pk'], ),
    sa.PrimaryKeyConstraint('sea_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sea_weather')
    op.drop_table('item_retail')
    op.drop_table('location')
    op.drop_table('item')
    op.drop_table('ground_weather')
    # ### end Alembic commands ###
